(defpackage stw.form
  (:use :cl :template)
  (:nicknames :form)
  (:import-from
   :stw.util
   :map-tree-depth-first
   :awhen
   :aif
   :self
   :ensure-list
   :ensure-string
   :get-float)
  (:import-from
   :closer-mop
   :slot-definition-name
   :slot-definition-type
   :slot-definition-initargs)
  (:import-from
   :contextl
   :define-layered-function
   :define-layered-method
   :define-layered-class
   :deflayer
   :with-active-layers
   :call-next-layered-method
   :partial-class-base-initargs
   :singleton-class)
  (:import-from
   :cl-ppcre
   :scan
   :scan-to-strings)
  (:import-from
   :cl-comp
   :slot-definition-class
   :serialized-p
   :serialize
   :define-base-class
   :map-filtered-slots
   :filter-slots-by-type
   :find-slot-definition
   :initialize-in-context
   :object-to-plist)
  (:import-from
   :xml.parse
   :branch-node
   :child-nodes
   :the-content
   :*indent*
   :indent-string
   :serialize-object
   :query-select
   :query-select-all)
  (:import-from
   :html.parse
   :serialize-object
   :define-html-node
   :html-parse-id
   :html-class
   :html-parse-for
   :html-parse-value
   :html-parse-input-list
   :html-parse-input-min
   :html-parse-input-max
   :html-parse-name
   :html-parse-multiple
   :html-parse-disabled
   :html-parse-required
   :html-parse-pattern
   :html-parse-value
   :html-parse-minlength
   :html-parse-maxlength
   :html-parse-checked
   :input-type
   :div
   :form
   :fieldset
   :legend
   :label
   :text-node)
  (:import-from
   :sanitize
   :sanitize
   :text-only)
  (:import-from
   :local-time
   :timestamp<=
   :parse-timestring
   :format-timestring
   :+asctime-format+)
  (:export
   :form-class
   :form-layer
   :define-form
   :render-template
   :validate-form
   :validate-fields
   :validate-field
   :validate-form-error
   :validate-field-error
   :signal-convert
   :store-slot))
