(defpackage stw.form
  (:use :cl :template)
  (:nicknames :form)
  (:import-from
   :stw.util
   :map-tree-depth-first
   :awhen
   :self
   :ensure-list
   :ensure-string)
  (:import-from
   :closer-mop
   :slot-definition-name
   :slot-definition-type
   :slot-definition-initargs)
  (:import-from
   :contextl
   :define-layered-function
   :define-layered-method
   :define-layered-class
   :deflayer
   :with-active-layers
   :partial-class-base-initargs)
  (:import-from
   :cl-comp
   :slot-definition-class
   :serialized-p
   :serialize
   :define-base-class
   :map-filtered-slots
   :initialize-in-context)
  (:import-from
   :xml.parse
   :branch-node
   :child-nodes
   :*indent*
   :indent-string
   :serialize-object)
  (:import-from
   :html.parse
   :serialize-object
   :define-html-node
   :html-parse-id
   :html-class
   :html-parse-for
   :html-parse-value
   :html-parse-input-list
   :html-parse-name
   :html-parse-multiple
   :input-type
   :div
   :form
   :fieldset
   :legend
   :label
   :text-node)
  (:import-from
   :sanitize
   :clean
   :+default+)
  (:export
   :form-class
   :form-layer))
